name:                cautious
version:             0.0.0.0
category:            Testing
github:              "Nickske666/cautious"
license:             BSD3
author:              "Nick Van den Broeck"
maintainer:          "nick.van.den.broeck666@gmail.com"
copyright:           "2018 Nick Van den Broeck"
description:         A Cautious monad "Monoid w => Cautious w e a" which keeps track of the success of a task. The options are "CautiousWarning w a" (where "CautiousWarning mempty a" represents "success") and "CautiousError e".
                     In addition, there is a monadtransformer "Monad m, Monoid w => CautiousT w e m a"
synopsis:            Keep track of warnings and errors during calculations.
extra-source-files:
- README.md
- ChangeLog.md
dependencies:
- base >= 4.11 && < 5
- hspec -any
- hspec-discover -any
- validity -any
- transformers -any
- QuickCheck >= 2.9 && < 2.11
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Import
  - Cautious.Cautious
  - Cautious.CautiousT
  default-extensions: NoImplicitPrelude
tests:
  cautious-test:
    main:                Spec.hs
    source-dirs:         test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cautious
    - hspec
    - genvalidity-hspec
    - genvalidity
    - QuickCheck
